### ISSUE TITLE
Heatsinks

### ISSUE THREAD

**Issue by nicopace** [LibreRouterOrg/board#10]
Heatsinks are not fitted to the QCA9558 and PA chips, or the PCIe radio modules.

The QCA9558 chip surface runs 25-30C above ambient temperature with no heatsink at idle.
The chips are likely to overheat and fail with high data throughput.

**Comment by tgillett** [comment]
Being addressed by Edwin in board re-design.
Moved to Phase 2 testing.

**Comment by dragino** [comment]
We will work on this on Core9558 module in re-design.

**Comment by spiccinini** [comment]
mPCI modules have heatsink but Core9558 v0.2 board doesn't have heatsink in QCA9558.

**Comment by spiccinini** [comment]
Fixed!
