### ISSUE TITLE
Input voltage is <= 30V  

### ISSUE THREAD

**Issue by spiccinini** [LibreRouterOrg/board#25]
There is a problem when voltage go over 30V (with and without PoE). Consumption goes from 4.7W@30V to 7W@32V. The component that gets very hot seems to be V1 BC301N-D Gas Discharge Tube.
So the usable range is 8V to 29V at least in the board I measured.

**Comment by tgillett** [comment]
The BC301N-D should have a breakdown voltage of 300V. Below this value it should appear as an open circuit.
Does the component have identifying markings on it?
Perhaps it is an incorrect component in that position.

**Comment by spiccinini** [comment]
This is the component that gets really hot (all the area is hot but this is specially hot or it conducts heat a lot more than the others as I am measuring with my finger)
![hot_component](https://user-images.githubusercontent.com/500841/49407307-d645e680-f736-11e8-948a-05e3ab8ea547.jpg)

I will try to unsolder and test again without V1, but yes, you are right that this component shouldn't be the problem.

**Comment by dragino** [comment]
Do we need to power it for over 30V?

**Comment by spiccinini** [comment]
No, it is not a requirement as far as I know. I opened an issue because the input range was advertised from 8 to 36. 
We can shrink the input range from 8 to 29?, but I think it is interesting to know which component is the culprit (in case we want to extend the range) so we can know for sure the range, I only measured one device and maybe another device has lower input range. 
I didn't have the time to review all the input components datasheets.  

Other important things I noted in  the circuit:
* Input capacitor C76 is 25V rated. This is far from good if we want to allow 24V in the range. Also this is an electrolytic capacitor we should use ceramic or tantallum if posible. Proper derating depends on type of capacitor.

**Comment by spiccinini** [comment]
Diode D1 (SMBJ24CA)  is a 24V Transient Voltage Suppression Diode. This should be the culprit but I didn't have the time to test it. We should change this for a SMBJ40CA that is rated 40V

**Comment by spiccinini** [comment]
I measured up to 32V of input voltage without heat removing D1. (So BC301N-D Gas Discharge Tube is not the problem)

The proposed changes are:
*  change D1 to SMBJ40CA  (that can handle up to 40V).
* change C76 to a cap of at least 36V

**Comment by spiccinini** [comment]
Chages done in MegaBoard v1.2 eagle project.

**Comment by spiccinini** [comment]
Fixed!
