### ISSUE TITLE
Better PoE power handling in both LAN and WAN ports

### ISSUE THREAD

**Issue by spiccinini** [LibreRouterOrg/board#34]
We should add a low voltage diode from the PoE to the PoE pass port as some current is going from the PoE_pass that at least powers a LED, being very confusing.

**Comment by spiccinini** [comment]
Maybe we can make PoE work in both ports as input but for poe pass only one port is the input.

**Comment by xcancerberox** [comment]
Proposal: duplicate the circuit of poe_injection and add diodes to ensure the current circuit.

![image](https://user-images.githubusercontent.com/1068399/71847204-99cc8300-30cc-11ea-96c3-4adf98925a55.png)

**Comment by xcancerberox** [comment]
Add hardware switch for default state of the POE injection enable.

![image](https://user-images.githubusercontent.com/1068399/71847283-c84a5e00-30cc-11ea-9e1e-a7de329957d0.png)

**Comment by xcancerberox** [comment]
Added by 0140862596738967a777f8743e4311cc6e76c370 and f2e57b348a968a50a00aaf77966036c01f5a0f3e
