### ISSUE TITLE
Improve impedance of PCIe routing

### ISSUE THREAD

**Issue by spiccinini** [LibreRouterOrg/board#54]
Differential impedance must be 100ohm. 

Current Mega board calculated impedance is 130ohm.
![photo5150119405626173508](https://user-images.githubusercontent.com/500841/70528782-c3c27200-1b2d-11ea-8e90-fe113e4981f6.jpg)

One proposed solution:
![photo5150119405626173509](https://user-images.githubusercontent.com/500841/70528963-316e9e00-1b2e-11ea-9eee-5e82689b8469.jpg)

**Comment by xcancerberox** [comment]
The PCIe connector pad size is 0.6mm. I'm using that for track width and 8mils for separation:

![image](https://user-images.githubusercontent.com/1068399/70549166-0c048300-1b74-11ea-9e85-be777f745d12.png)

**Comment by xcancerberox** [comment]
Change decoupling capacitor network. Originally two 47uF where close to una pcie and two 33pF capacitor to the other pcie.

![image](https://user-images.githubusercontent.com/1068399/70981535-9d647f80-20b5-11ea-9f2c-cd6a4442a457.png)

![image](https://user-images.githubusercontent.com/1068399/70981564-ad7c5f00-20b5-11ea-8362-4a2082ef98f9.png)

Separate one of each to each pcie.

**Comment by xcancerberox** [comment]
The routing whit the calculated impedance was added on f1ad32cfdfde17e03cad46a9efe0c93327818638

**Comment by xcancerberox** [comment]
Just for clarification, the final configuration for the differential pairs is:

![image](https://user-images.githubusercontent.com/1068399/73450206-377e3f80-4365-11ea-8c89-a22c272b9777.png)
