### ISSUE TITLE
Improve Ethernet differential pair impedance and reduce series resistance

### ISSUE THREAD

**Issue by xcancerberox** [LibreRouterOrg/board#57]
The differential routing of the ethernet lines is not compliant with the impedance nether with the carrying power.

**Comment by xcancerberox** [comment]
Fix on 4c0051eecfe6e593972a1cddfc6a8a67d895d060 and 2f6afb35d4b0d7b5d6529eec57b592b3f91f3a47

**Comment by spiccinini** [comment]
![image](https://user-images.githubusercontent.com/500841/72277941-aa6f8280-3611-11ea-95ff-4917f34f399e.png)
